title:             Clean Blog | Web Developer
email:             huuduc.uneti@gmail.com
brand:             Clean Blog
description:       A blog of web developer
author:            Clean Blog
baseurl:           "/"
url:               "http://ducdh.github.io"

# Social Profiles
twitter_username:  huuduc2107
github_username:   dhduc
facebook_username: huuduc.a7

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
